base_url: https://eager-goodall-4d4f5f.netlify.app
index_md: Hello!ğŸ‘‹ğŸ˜ƒ\n\nI'm a software engineer based in the UK.
title: ğŸš€ Will Clarke
rss_title: Will Clarke's Blog
rss_description: Some random ramblings of a sleep-deprived software engineer
